# Site settings

title: vedransekara # Title of your site
email: vedransekara@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Vedran Sekara - doing data science, physics, math and other cool stuff. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vedransekara.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     vedransekara  # Replace this with your Twitter username
github_username:      vedransekara  # Replace this with your GitHub username
linkedin_username:    vedran-sekara-160284a2  # Replace this with your LinkedIn username
#google_plus_username: example  # Replace this with your Google+ username
#facebook_username:    example  # Replace this with your Facebook username
#dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
